Adjust ffmpeg configuration command to dynamically fetch CPU architec…
jaredpetersen/raspi-live pull request #21
Opened 2019-03-02 22:05 UTC by nicklasfrahm

This is a potential fix for #20.

2019-03-03 10:46 UTC, nicklasfrahm commented
@jaredpetersen I've updated it. It should get the core count and CPU architecture only from very basic bash commands. I will test it on my 3B+ as soon as I am home and I will also check if I have other RPis lying around to test it. Currently, I've only validated these command on my [Windows Subsystem Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) with Ubuntu 16.04.

2019-03-05 18:49 UTC, jaredpetersen commented
@nicklasfrahm Were you able to confirm that this works on your raspberry pi 3B+ and some of your other pis? Otherwise, looks great to me.

2019-03-05 19:40 UTC, nicklasfrahm commented
@jaredpetersen Specifying a specific arch for `arm`, either `armhf`, `armel` or `armv7l`, is unnecessary, as [this](https://github.com/FFmpeg/FFmpeg/blob/master/configure#L4726) shows. I have removed it and verified that the command for the CPU thread count works on the following devices:
- Raspberry Pi 3B+
- Raspberry Pi 3B

2019-03-05 19:45 UTC, nicklasfrahm commented
Would you mind if I also throw in an editor config to prevent problems with whitespaces in PRs? Something like this:

```txt
# top-most .editorconfig file
root = true

[*]
end_of_line = lf
insert_final_newline = true
charset = utf-8
indent_style = space
indent_size = 2
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false
```

2019-03-06 02:03 UTC, jaredpetersen requested changes
Glad that you were able to test this on a few raspberry pis. Take care of the "Now" feedback and I'll merge it right away.

2019-03-06 02:03 UTC, jaredpetersen commented on README.md
> +2. Now, run `sudo make -j$(grep -c ^processor /proc/cpuinfo)` to build FFmpeg and get a cup of coffee or two. This will take a while.
Remove the "Now," and just stick with "Run". It's not necessary and avoids having to deal with the debate over whether or not it's grammatically correct to put a comma after "Now" at the start of a sentence.

2019-03-06 02:03 UTC, jaredpetersen commented on README.md
> +sudo ./configure --arch=arm --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree
Nice job on digging into FFmpeg's configure command. Wouldn't have even thought to look there. 👍

2019-03-06 02:05 UTC, jaredpetersen commented
@nicklasfrahm I'd rather not commit any editor config files since there's a million different configs out there. I think it would be better if there was a linter or something like prettier installed that ensured that none of that was committed anyways. Not for this pull request though.

2019-03-06 07:42 UTC, nicklasfrahm commented on README.md
> +2. Now, run `sudo make -j$(grep -c ^processor /proc/cpuinfo)` to build FFmpeg and get a cup of coffee or two. This will take a while.
Sorry, I am not a native English speaker, but I appreciate every correction. 👍

2019-03-06 07:43 UTC, nicklasfrahm commented
@jaredpetersen All comments are fixed and I will have a look at #22.

2019-03-06 15:46 UTC, jaredpetersen approved these changes
Looks great 👍

2019-03-06 15:52 UTC, jaredpetersen commented on README.md
> +2. Now, run `sudo make -j$(grep -c ^processor /proc/cpuinfo)` to build FFmpeg and get a cup of coffee or two. This will take a while.
Don't worry about it! Your written English is excellent. The "issue" around whether or not to put a comma after the word "Now" at the start of a sentence is apparently debated and it seems that both approaches are correct. It's just not something you see very often, so removing the word entirely avoids having to deal with the problem at all.

2019-03-06 15:53 UTC, merged